import React from 'react';

interface TranscriptViewProps {
  transcript: string;
}

const TranscriptView: React.FC<TranscriptViewProps> = ({ transcript }) => {
  const copyToClipboard = () => {
    navigator.clipboard.writeText(transcript);
  };

  return (
    <div className="w-full max-w-2xl mx-auto mt-8 animate-fade-in-up">
      <div className="flex items-center justify-between mb-3 px-1">
        <h2 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-emerald-600"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
          Urdu Transcript
        </h2>
        <div className="flex gap-2">
            <button 
                onClick={copyToClipboard}
                className="text-xs flex items-center gap-1 px-3 py-1.5 bg-white border border-gray-200 text-gray-600 rounded-full hover:bg-gray-50 hover:text-emerald-600 transition-colors"
            >
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                Copy Text
            </button>
        </div>
      </div>
      
      <div className="relative bg-white rounded-2xl shadow-sm border border-emerald-100 overflow-hidden">
        {/* Decorative header line */}
        <div className="h-1 bg-gradient-to-r from-emerald-400 to-emerald-600 w-full"></div>
        
        <div 
            className="p-8 min-h-[200px] max-h-[600px] overflow-y-auto custom-scrollbar font-urdu text-xl leading-relaxed text-right text-gray-800"
            dir="rtl"
        >
          {transcript.split('\n').map((line, index) => (
             line.trim() ? <p key={index} className="mb-4">{line}</p> : <br key={index} />
          ))}
        </div>
        
        <div className="bg-gray-50 px-6 py-3 border-t border-gray-100 flex justify-between items-center">
            <span className="text-xs text-gray-400">Generated by Gemini 2.5 Flash</span>
            <span className="text-xs text-gray-400">{transcript.length} chars</span>
        </div>
      </div>
    </div>
  );
};

export default TranscriptView;